---
title: "Data visualization"
author: "Henrik Husberg, henrik.husberg@helsinki.fi"
date: "20.04 2020"
output: 
  html_document:
    theme: cerulean
    toc: true
    toc_depth: 2
    fig_caption: true
    fig_width: 6
    fig_height: 4
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Data visualizations

## Circles plot 1


```{r echo=FALSE}
setwd("C:/Users/hehusb/Nextcloud/ILS/Tark/ILS2/Rfiles")
library(packcircles)
library(ggplot2)
library(viridisLite)
library(viridis)
library(ggiraph)

#Datan lukeminen csv:stä (UTF-8) ja muuttaminen dataframiksi
#Tässä data on "Mihin tarvitsee tukea". Excelissä laskettu yhteen vastaukse kolumneittain ennen R:ään siirtoa.
data_avo <- read.csv(file="C:/Users/hehusb/Nextcloud/ILS/Tark/ILS2/Rfiles/avoimet_kat.csv", header=TRUE, sep=";")
data_avo_df <- as.data.frame(t(data_avo))
#data_avo_df

#packcircles:in layoutin valinta ja määritys sekä uusien, ympyröiden määrittävien muuttujien lisääminen dataan
packing <- circleProgressiveLayout(data_avo_df, sizetype='area')
data_avo_df <- cbind(data_avo_df, packing)
#data_avo_df

#ryhmien, eli ympyröden nimien lisääminen dataan
groups <- c("Uppmuntra och motivera", "Håll personlig kontakt", "Ta vara på färdigt material", "Skapa nytt med hjälp av tekniken", "Tydliggör och strukturera", "Ordna gemensamma stunder för undervisning", "Övriga tips")
#groups
data_avo_df <- cbind(data_avo_df, groups)
#data_avo_df

# interaktiivinen datan lisäys
data_avo_df$text <- paste("Kategori: ",data_avo_df$groups, "\n", "Antal:", data_avo_df$V1, "\n", "")
#data_avo_df

#ympyröiden plottaus
#plot(data_avo_df$radius, data_avo_df$V1)

dat.gg <- circleLayoutVertices(packing, npoints=50)

p <- ggplot() + 
  geom_polygon_interactive(data = dat.gg, aes(x, y, group = id, fill=id, tooltip = data_avo_df$text[id], data_id = id), colour = "black", alpha = 0.6) +  
  scale_fill_viridis() +
  geom_text(data = data_avo_df, aes(x, y, label=groups)) +
#  scale_size_continuous(range = c(1,4)) +  
  theme_void() + 
  theme(legend.position="none") +
  coord_equal()  

widg <- ggiraph(ggobj = p, width_svg = 7, height_svg = 7)
widg  

#library(htmlwidgets)
#saveWidget(widg, file=paste0( getwd(), "/circular_packing_interactive.html"))
```

## Circles plot 2
```{r echo=FALSE}
#Datan lukeminen csv:stä (UTF-8) ja muuttaminen dataframiksi
#Tässä data on "Mihin tarvitsee tukea". Excelissä laskettu yhteen vastaukse kolumneittain ennen R:ään siirtoa.
data_avo <- read.csv(file="C:/Users/hehusb/Nextcloud/ILS/Tark/ILS2/Rfiles/haasteet_opvaik_avot.csv", header=TRUE, sep=";")
data_avo_df <- as.data.frame(t(data_avo))
#data_avo_df

#packcircles:in layoutin valinta ja määritys sekä uusien, ympyröiden määrittävien muuttujien lisääminen dataan
packing <- circleProgressiveLayout(data_avo_df, sizetype='area')
data_avo_df <- cbind(data_avo_df, packing)
#data_avo_df

#ryhmien, eli ympyröden nimien lisääminen dataan
groups <- c("Kodin tuki", "Motivointi", "Selkeät ohjeet", "Tuki", "Tavoittaminen", "Toiminnanohjaus", "Tietotekniset haasteet", "Oppilaan hyvinvointi", "Opettajan työhön liittyvät asiat")
#groups
data_avo_df <- cbind(data_avo_df, groups)
#data_avo_df

# interaktiivinen datan lisäys
data_avo_df$text <- paste("Kategoria: ",data_avo_df$groups, "\n", "Lukumäärä:", data_avo_df$V1, "\n", "")
#data_avo_df

#ympyröiden plottaus
#plot(data_avo_df$radius, data_avo_df$V1)

dat.gg <- circleLayoutVertices(packing, npoints=50)

p <- ggplot() + 
  geom_polygon_interactive(data = dat.gg, aes(x, y, group = id, fill=id, tooltip = data_avo_df$text[id], data_id = id), colour = "black", alpha = 0.6) +  
  scale_fill_viridis() +
  geom_text(data = data_avo_df, aes(x, y, label=groups)) +
#  scale_size_continuous(range = c(1,4)) +  
  theme_void() + 
  theme(legend.position="none") +
  coord_equal()  

widg <- ggiraph(ggobj = p, width_svg = 7, height_svg = 7)
widg  

```

## Barplots 2
```{r echo=FALSE}
#Datan lukeminen csv:stä (UTF-8) ja muuttaminen dataframiksi
#Tässä data on "Mihin tarvitsee tukea". Excelissä laskettu yhteen vastaukse kolumneittain ennen R:ään siirtoa.
data_avo_bar <- read.csv(file="C:/Users/hehusb/Nextcloud/ILS/Tark/ILS2/Rfiles/haasteet_S2_avot.csv", header=TRUE, sep=";")
data_avo_bar_df <- as.data.frame(t(data_avo_bar))
#summary(data_avo_bar_df)
#data_avo_bar_df

groups_bar <- c("Motivointi", "Kodin tuki", "Selkeät ohjeet", "Tuki", "Tavoittaminen", "Toiminnanohjaus", "Tietotekniset haasteet", "Kieli")
#groups
data_avo_bar_df <- cbind(data_avo_bar_df, groups_bar)
p<-ggplot(data=data_avo_bar_df, aes(x=groups_bar, y=V1)) +
  geom_bar(stat="identity", fill="steelblue") + 
  scale_fill_hue(c = 40) +
  theme(axis.text.x = element_text(angle=45, hjust=1, vjust = 1),
          axis.title = element_blank(),
          plot.margin = margin(t = 20, r = 10, b = 10, l = 10))
p
#  scale_fill_hue(c = 40) +
#  theme(legend.position="none")
```